### ISSUE TITLE
Links are spelled out character by character

### ISSUE THREAD

**Issue by 3cki** [nizarbamida/tiktok_vid_gen#2]
Whenever a comment contains a link, it will be spelled out like "h-t-t-p-:-/-/..." which can take up the whole video. This is often the case when a link is connected to text like:

[This is a link to Google.](https://google.com)

The bot will first read the text (in this case "This is a link to Google.") and then it will spell out the actual link (In this case "h-t-t-p-:-/-/-google-.-com")

**Comment by nizarbamida** [comment]
can you please re create this issue into this new repo https://github.com/nizarbamida/RedditVideoMakerBot, this one will get deleted, i will try to push fixes this week
thanks
